<Project>
    <PropertyGroup Condition="'$(SerilogIsStructureValueSupported)' == '' and '$(PublishTrimmed)' == 'true'">
        <SerilogIsStructureValueSupported>false</SerilogIsStructureValueSupported>
    </PropertyGroup>

    <ItemGroup Condition="'$(SerilogIsStructureValueSupported)' != ''">
        <RuntimeHostConfigurationOption
        Include="Serilog.Capturing.IsStructureValueSupported"
        Value="$(SerilogIsStructureValueSupported)" Trim="true" />
    </ItemGroup>
</Project>
